# Generated by Django 6.0.7 on 2026-07-20 21:32

import django.core.validators
import django.db.models.deletion
import masjids.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Masjid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='Used in subdomain/URL, e.g. masjid-noor', unique=True)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('firqa', models.CharField(blank=True, max_length=100, null=True)),
                ('google_maps_link', models.URLField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', help_text="IANA timezone name, e.g. 'Europe/London', 'Asia/Karachi'", max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='masjid_logos/')),
                ('intro_video', models.FileField(blank=True, help_text='Optional intro video, max 30 seconds', null=True, upload_to='masjid_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'webm']), masjids.models.validate_masjid_video_duration])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DonationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(max_length=150)),
                ('account_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=50)),
                ('sort_code', models.CharField(blank=True, max_length=20, null=True)),
                ('iban', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('masjid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_details', to='masjids.masjid')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MasjidImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='masjid_images/')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (0-3)')),
                ('masjid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='masjids.masjid')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MasjidTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_color', models.CharField(default='#0F6B47', max_length=7)),
                ('secondary_color', models.CharField(default='#F5A623', max_length=7)),
                ('font_family', models.CharField(default='Inter', max_length=50)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='masjid_backgrounds/')),
                ('masjid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='masjids.masjid')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
