# Generated by Django 6.0.7 on 2026-07-24 22:33

import django.core.validators
import masjids.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masjids', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masjid',
            name='intro_video',
            field=models.FileField(blank=True, help_text='Optional intro video, max 30 seconds and 30MB', null=True, upload_to='masjid_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'webm']), masjids.models.validate_masjid_video_size, masjids.models.validate_masjid_video_duration]),
        ),
    ]
