# Generated by Django 6.0.7 on 2026-07-20 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masjids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JummaTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('khutbah_start', models.TimeField()),
                ('jamaat_time', models.TimeField()),
                ('masjid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jumma_times', to='masjids.masjid')),
            ],
            options={
                'ordering': ['date', 'jamaat_time'],
            },
        ),
        migrations.CreateModel(
            name='PrayerTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('fajr_start', models.TimeField()),
                ('fajr_jamaat', models.TimeField()),
                ('duhr_start', models.TimeField()),
                ('duhr_jamaat', models.TimeField()),
                ('asr_start', models.TimeField()),
                ('asr_jamaat', models.TimeField()),
                ('maghrib_start', models.TimeField()),
                ('maghrib_jamaat', models.TimeField()),
                ('isha_start', models.TimeField()),
                ('isha_jamaat', models.TimeField()),
                ('sunrise', models.TimeField(blank=True, null=True)),
                ('sunset', models.TimeField(blank=True, null=True)),
                ('noon', models.TimeField(blank=True, null=True)),
                ('masjid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='masjids.masjid')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('masjid', 'date')},
            },
        ),
    ]
